### ISSUE TITLE
Collect data on crises, organizations, and people.

### ISSUE THREAD

**Issue by zjgoodman** [zjg95/cs373-idb#12]
Identify common attributes of the data and insure that every data item has a value for that attribute.
Make sure to collect enough data to make it a rich experience.
Sources of the data must be identified.
The data must be collected programmatically.

**Comment by sdragoon** [comment]
Learning beautifulsoup for extraction, will post as a learn more

**Comment by zjgoodman** [comment]
Temporary data:
------------ regions
The North:
    Capitol:
        Winterfell
    Ruling Family:
        Stark

Stormlands:
    Capitol:
        Storm's End
    Ruling Family:
        Baratheon

Westerlands:
    Capitol:
        Casterly Rock
    Ruling Family:
        Lannister

-------------- castles

Winterfell:
    Location:
        The North
    Ruling Family:
        Stark

Storm's End:
    Location:
        Stormlands
    Ruling Family:
        Baratheon

Casterly Rock:
    Location:
        West
    Ruling Family:
        Lannister

--------------- people

Ned Stark
    House:
        Stark
    Titles:
        Lord of Winterfell
        Warden of the North
    Status:
        Dead
    Bio:
        Ned is cool

Robert Baratheon
    House:
        Baratheon
    Titles:
        Protector of the realm
        King
    Status:
        Dead
    Bio:
        He's loves women

Tywin Lannister
    House:
        Lannister
    Titles:
        Lord of Casterly Rock
    Status:
        Dead
    Bio:
        Tywin is pretty scary

**Comment by sdragoon** [comment]
See soup.txt, needs formatting still but data is gathered.

**Comment by sdragoon** [comment]
see formatted_soup.txt, now formatted with a fair amount of data.
