### ISSUE TITLE
Write an initial technical report using a GitHub Wiki.

### ISSUE THREAD

**Issue by zjgoodman** [zjg95/cs373-idb#21]
The audience comprises other software developers, as opposed to users.
For this phase it must be at least 2500 words.
Document the RESTful API and the models well.
Format the report clearly, attractively, and consistently, using good headers, figures, and grammar.

**Comment by sdragoon** [comment]
Currently sitting at ~2000 words, just need people to add in their design/tool section and then unit tests.
